name: Rust CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    name: Code Quality and Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Enable Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Check code formatting
        run: cargo fmt --check

      - name: Run Clippy linter
        run: cargo clippy -- -D warnings

      - name: Run tests
        run: cargo test --verbose

